function f = restoring_force(X,Y,omega_1,omega_2)
%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    20-Sep-2024 15:43:16

t2 = X.^2;
t3 = Y.^2;
t4 = omega_2.^2;
t5 = 1.0./omega_1.^2;
t6 = (t4.*t5)./2.0;
t7 = t6+1.0./2.0;
f = [t2.*(3.0./2.0)+t3./2.0+X.^3.*t7+X.*(t3.*t7+Y.*t4.*t5+1.0);t2.*t6+Y.^3.*t7+Y.*(X+t2.*t7+t4.*t5)+t3.*t4.*t5.*(3.0./2.0)];
end
